#### Numpy ndarray 

In [1]:
import xgboost
import lightgbm 
import sklearn 
import numpy as np  
import matplotlib.pyplot as plt 

In [17]:
list_py = [1, 2, 3]
print(f"list_py type : {type(list_py)}, \n{list_py}")
arr_np1 = np.array(list_py)
print(f"arr_np1 type : {type(arr_np1)}, \n{arr_np1}")
print(f"arr_np1 shape : {arr_np1.shape}")


arr_np2 = np.array([[1, 2, 3], 
                    [4, 5, 6]])

print(f"arr_np2 type : {type(arr_np2)} \n{arr_np2}")
print(f"arr_np2 shape : {arr_np2.shape}")


arr_np3 = np.array([[1, 2, 3]])
print(f"arr_np3 type {type(arr_np3)} \n{arr_np3}")
print(f"arr_np3 shape {arr_np3.shape}")

list_py type : <class 'list'>, 
[1, 2, 3]
arr_np1 type : <class 'numpy.ndarray'>, 
[1 2 3]
arr_np1 shape : (3,)
arr_np2 type : <class 'numpy.ndarray'> 
[[1 2 3]
 [4 5 6]]
arr_np2 shape : (2, 3)
arr_np3 type <class 'numpy.ndarray'> 
[[1 2 3]]
arr_np3 shape (1, 3)


In [16]:
print(f"arr_np1.ndim : {arr_np1.ndim}")
print(f"arr_np2.ndim : {arr_np2.ndim}")
print(f"arr_np3.ndim : {arr_np3.ndim}")

arr_np1.ndim : 1
arr_np2.ndim : 2
arr_np3.ndim : 2


#### Numpy ndarray datatype 

In [21]:
list_py1 = [1, 2, 3]
print(f"list_py1 type : {type(list_py1)}\n {list_py1}")

arr_np = np.array(list_py1)
print(f"arr_np type : {type(arr_np)} datatype {arr_np.dtype}")
print(f"{arr_np}")

list_py1 type : <class 'list'>
 [1, 2, 3]
arr_np type : <class 'numpy.ndarray'> datatype int32
[1 2 3]


In [23]:
list_py2 = [1, 2, 3, "test"]
print(f"list_py2 type : {type(list_py2)}\n {list_py2}")

arr_np = np.array(list_py2)
print(f"arr_np type : {type(arr_np)} datatype {arr_np.dtype}")
print(f"{arr_np}")

list_py2 type : <class 'list'>
 [1, 2, 3, 'test']
arr_np type : <class 'numpy.ndarray'> datatype <U11
['1' '2' '3' 'test']


In [29]:
list_py3 = [1, 2, 3, 4.0]
arr_np = np.array(list_py3)
print(f"arr_np type : {type(arr_np)} datatype {arr_np.dtype}")
print(f"{arr_np}")

arr_np type : <class 'numpy.ndarray'> datatype float64
[1. 2. 3. 4.]


In [33]:
vec_int1 = np.array([1, 2, 3])
print(f"vec_int1 dtype: {vec_int1.dtype} \n{vec_int1}")
vec_float1 = vec_int1.astype("float64")
print(f"vec_float1 dtype: {vec_float1.dtype} \n{vec_float1}")

vec_float2 = np.array([1.2, 1.1, 0.0])
vec_int2 = vec_float2.astype("int64")
print(f"vec_int2 dtype: {vec_int2.dtype} \n{vec_int2}")


vec_int1 dtype: int32 
[1 2 3]
vec_float1 dtype: float64 
[1. 2. 3.]
vec_int2 dtype: int64 
[1 1 0]


#### Create ndarray 
- arange 
- zeros 
- ones 

In [39]:
sequence_array = np.arange(10)
print(f"sequence_array \nshape : {sequence_array.shape} \ndimension : {sequence_array.ndim} \ndtype : {sequence_array.dtype}\n{sequence_array}")

sequence_array 
shape : (10,) 
dimension : 1 
dtype : int32
[0 1 2 3 4 5 6 7 8 9]


In [47]:
zeros_array = np.zeros((3, 2), dtype="int32")
print(f"zeros_array \nshape : {zeros_array.shape} \ndimension : {zeros_array.ndim} \ndtype : {zeros_array.dtype} \n{zeros_array}")

print("\n")
ones_array = np.ones((3, 2))
print(f"ones_array \n{ones_array.shape} \ndimension : {ones_array.ndim} \ndtype: {ones_array.dtype} \n{ones_array}")


zeros_array 
shape : (3, 2) 
dimension : 2 
dtype : int32 
[[0 0]
 [0 0]
 [0 0]]


ones_array 
(3, 2) 
dimension : 2 
dtype: float64 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### ndarray reshape

In [50]:
array_a = np.arange(10)
print(f"array_a : {array_a}")

array_b = array_a.reshape(2, 5)
print(f"array_b : \n{array_b}")

array_c = array_a.reshape(5, 2)
print(f"array_c : \n{array_c}")


array_a : [0 1 2 3 4 5 6 7 8 9]
array_b : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
array_c : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [51]:
array_a = np.arange(10)
print(f"array_a : {array_a}")

array_b = array_a.reshape(-1, 5)
print(f"array_a.reshape(-1, 5) : \n{array_b}")


array_c = array_a.reshape(5, -1)
print(f"array_a.reshape(5, -1) : \n{array_b}")

array_a : [0 1 2 3 4 5 6 7 8 9]
array_a.reshape(-1, 5) : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
array_a.reshape(5, -1) : 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
print("=============Vector=============")
vec_array = np.arange(8)
print(f"vec_array \nndim : {vec_array.ndim} \nshape : {vec_array.shape} \n{vec_array.tolist()}")
print("============= Vector -> Tensor =============")

ten_array = vec_array.reshape(2, 2, 2)
print(f"ten_array \nndim : {ten_array.ndim} \nshape : {ten_array.shape} \n{ten_array.tolist()}")

print("============= Tensor -> Matrix =============")

mat_array = ten_array.reshape(-1, 1)
print(f"mat_array \nndim : {mat_array.ndim} \nshape : {mat_array.shape} \n{mat_array.tolist()}")

print("============= Tensor -> Vector =============")
vec_array = ten_array.reshape(-1, )
print(f"vec_array \nndim : {vec_array.ndim} \nshape : {vec_array.shape} \n{vec_array.tolist()}")


=============Vector=============
vec_array 
ndim : 1 
shape : (8,) 
[0, 1, 2, 3, 4, 5, 6, 7]
============= Vector -> Tensor =============
ten_array 
ndim : 3 
shape : (2, 2, 2) 
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
============= Tensor -> Matrix =============
mat_array 
ndim : 2 
shape : (8, 1) 
[[0], [1], [2], [3], [4], [5], [6], [7]]
============= Tensor -> Vector =============
vec_array 
ndim : 1 
shape : (8,) 
[0, 1, 2, 3, 4, 5, 6, 7]


#### Indexing Slicing 
- Indexing 
- Slicing 
- Fancy indexing 
- Boolean indexing 

In [80]:
vec_array = np.arange(start=1, stop=10)
print(f"vec_array  \nndim : {vec_array.ndim} \nshape : {vec_array.shape} \n{vec_array.tolist()}")

print("\n=============Vector Indexing =============")
print(f"vec_array[2] : {vec_array[2]} ")
print(f"vec_array[-1] : {vec_array[-1]} , {type(vec_array[-1])}")
print(f"vec_array[-2] : {vec_array[-2]} , {type(vec_array[-2])}")

vec_array  
ndim : 1 
shape : (9,) 
[1, 2, 3, 4, 5, 6, 7, 8, 9]
vec_array[2] : 3 
vec_array[-1] : 9 , <class 'numpy.int32'>
vec_array[-2] : 8 , <class 'numpy.int32'>


In [93]:
vec_array=np.arange(start=1, stop=10, step=1)
print(f"vec_array \nndim : {vec_array.ndim} \nshape : {vec_array.shape} \n{vec_array.tolist()}")

print("============= Vector -> Matrix =============")
mat_array = vec_array.reshape(3, 3)
print(f"mat_array \nndim : {mat_array.ndim} \nshape : {mat_array.shape} \n{mat_array.tolist()}")
for row in range(len(mat_array)):
    for col in range(len(mat_array[row])):
        print(f"mat_array[{row}][{col}] : {mat_array[row][col]}", end= " ")
    print()

print("\n=============Matrix Indexing =============")
print(f"mat_array index[0, 0] : {mat_array[0, 0]}")
print(f"mat_array index[0, 1] : {mat_array[1, 0]}")
print(f"mat_array index[1, 0] : {mat_array[0, 1]}")
print(f"mat_array index[2, 2] : {mat_array[2, 2]}")

vec_array 
ndim : 1 
shape : (9,) 
[1, 2, 3, 4, 5, 6, 7, 8, 9]
============= Vector -> Matrix =============
mat_array 
ndim : 2 
shape : (3, 3) 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat_array[0][0] : 1 mat_array[0][1] : 2 mat_array[0][2] : 3 
mat_array[1][0] : 4 mat_array[1][1] : 5 mat_array[1][2] : 6 
mat_array[2][0] : 7 mat_array[2][1] : 8 mat_array[2][2] : 9 

=============Matrix Indexing =============
mat_array index[0, 0] : 1
mat_array index[0, 1] : 4
mat_array index[1, 0] : 2
mat_array index[2, 2] : 9


In [104]:
vec_arr = np.arange(start=1, stop=10)
print(f"vec_arr \nndim : {vec_arr.ndim} \nshape : {vec_arr.shape} \n{vec_arr}")
print(f"vec_arr [0:3] = {vec_arr[0:3]} type : {type(vec_arr[0:3])}")
print(f"vec_arr [3:] = {vec_arr[3:]} type : {type(vec_arr[3:])}")
print(f"vec_arr [:] = {vec_arr[:]} type : {type(vec_arr[:])}")

vec_arr 
ndim : 1 
shape : (9,) 
[1 2 3 4 5 6 7 8 9]
vec_arr [0:3] = [1 2 3] type : <class 'numpy.ndarray'>
vec_arr [3:] = [4 5 6 7 8 9] type : <class 'numpy.ndarray'>
vec_arr [:] = [1 2 3 4 5 6 7 8 9] type : <class 'numpy.ndarray'>


In [122]:
mat_arr = vec_arr.reshape(3, 3)
print(f"mat_arr \nndim : {mat_arr.ndim} \nshape : {mat_arr.shape} \n{mat_arr.tolist()}")

print("\n=============Matrix Slicing =============")
print(f"mat_arr [0:2, 0:2] = {mat_arr[0:2, 0:2].tolist()}")
print(f"mat_arr [0:3, 1:3] = {mat_arr[0:3, 1:3].tolist()}")
print(f"mat_arr [1:3, :] = {mat_arr[1:3, :].tolist()}")
print(f"mat_arr [:2, 1:] = {mat_arr[:2, 1:].tolist()}")
print(f"mat_arr [:2, 0] = {mat_arr[:2, 0].tolist()}")


mat_arr 
ndim : 2 
shape : (3, 3) 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

=============Matrix Slicing =============
mat_arr [0:2, 0:2] = [[1, 2], [4, 5]]
mat_arr [0:3, 1:3] = [[2, 3], [5, 6], [8, 9]]
mat_arr [1:3, :] = [[4, 5, 6], [7, 8, 9]]
mat_arr [:2, 1:] = [[2, 3], [5, 6]]
mat_arr [:2, 0] = [1, 4]


In [131]:
print("\n=============Fancy Indexing=============")
vec_arr = np.arange(start=1, stop=10)
mat_arr = vec_arr.reshape(3, 3)
print(f"vec_arr \nndim : {vec_arr.ndim} \nshape : {vec_arr.shape} \n{vec_arr.tolist()}")
print("============= Vector Reshape -> Matrix  =============")
print(f"mat_arr \nndim : {mat_arr.ndim} \nshape : {mat_arr.shape} \n{mat_arr.tolist()}")


mat_arr2 = mat_arr[[0, 1], 2]
print(f"mat_arr[[0, 1], 2] \n{mat_arr2}" )

mat_arr3 = mat_arr[[0, 1], 0:2]
print(f"mat_arr[[0, 1], 0:2] \n{mat_arr3}" )


mat_arr4 = mat_arr[[0, 1]]
print(f"mat_arr[[0, 1]] \n{mat_arr4}" )



=============Fancy Indexing=============
vec_arr 
ndim : 1 
shape : (9,) 
[1, 2, 3, 4, 5, 6, 7, 8, 9]
============= Vector Reshape -> Matrix  =============
mat_arr 
ndim : 2 
shape : (3, 3) 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat_arr[[0, 1], 2] 
[3 6]
mat_arr[[0, 1], 0:2] 
[[1 2]
 [4 5]]
mat_arr[[0, 1]] 
[[1 2 3]
 [4 5 6]]


In [5]:
print("\n=============Boolean Indexing=============")
vec_arr = np.arange(start = 0, stop=10)
print(f"vec_arr \nndim : {vec_arr.ndim} \nshape : {vec_arr.shape} \n{vec_arr.tolist()}")

print(f"vec_arr > 5 {vec_arr > 5}")
vec_arr2 = vec_arr[vec_arr > 5]
print(f"vec_arr2 \nndim : {vec_arr2.ndim} \nshape : {vec_arr2.shape} \n{vec_arr2.tolist()}")



=============Boolean Indexing=============
vec_arr 
ndim : 1 
shape : (10,) 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
vec_arr > 5 [False False False False False False  True  True  True  True]
vec_arr2 
ndim : 1 
shape : (4,) 
[6, 7, 8, 9]


#### ndarray sort, argsort

In [15]:
vec_origin = np.array([3, 1, 9, 5])
print(f"original vector : {vec_origin}")

print("\n=============np.sort(ndarray)=============")
sort_origin = np.sort(vec_origin)
print(f"original vector : {sort_origin}")

print("\n=============ndarray.sort()=============")
vec_origin.sort()
print(f"original vector : {vec_origin}")

original vector : [3 1 9 5]

=============np.sort(ndarray)=============
original vector : [1 3 5 9]

=============ndarray.sort()=============
original vector : [1 3 5 9]


In [17]:
print("\n=============descending =============")
sort_origin_desc = np.sort(vec_origin)[::-1]
print(f"sort_origin_desc {sort_origin_desc}")


=============descending =============
sort_origin_desc [9 5 3 1]


In [23]:
mat_origin = np.array([[8, 12],
                       [7, 1]])

sort_axis0 = np.sort(mat_origin, axis=0)
print(f"sort_axis0 = \n{sort_axis0}")


sort_axis1 = np.sort(mat_origin, axis=1)
print(f"sort_axis1 = \n{sort_axis1}")

sort_axis0 = 
[[ 7  1]
 [ 8 12]]
sort_axis1 = 
[[ 8 12]
 [ 1  7]]


In [32]:
vec_origin = np.array([3, 1, 9, 5])
print(f"vec_origin : {vec_origin}")
sort_indices_desc = np.argsort(vec_origin)[::-1]
sort_indices_asc = np.argsort(vec_origin)
print(f"sord_indices_desc type :{type(sort_indices_desc)} {sort_indices_desc}")
print(f"sord_indices_asc type :{type(sort_indices_asc)} {sort_indices_asc}")

vec_origin : [3 1 9 5]
sord_indices_desc type :<class 'numpy.ndarray'> [2 3 0 1]
sord_indices_asc type :<class 'numpy.ndarray'> [1 0 3 2]


In [34]:
name_array = np.array(["John", "Mike", "Sarah", "Kate", "Samuel"])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc =  np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#### ndarray dot 

In [37]:
A = np.array([[1, 2, 3],
              [4 ,5, 6]])
B = np.array([[7, 8], 
              [9, 10], 
              [11, 12]])
print(f"A \nshape : {A.shape} \ndimension {A.ndim} \n{A}")
print(f"B \nshape : {B.shape} \ndimension {B.ndim} \n{B}")
dot_mat = np.dot(A, B)
print(f"dot_mat \nshape{dot_mat.shape} \ndimension{dot_mat.ndim} \n{dot_mat}") 

A 
shape : (2, 3) 
dimension 2 
[[1 2 3]
 [4 5 6]]
B 
shape : (3, 2) 
dimension 2 
[[ 7  8]
 [ 9 10]
 [11 12]]
dot_mat 
shape(2, 2) 
dimension2 
[[ 58  64]
 [139 154]]


#### ndarray transpose

In [41]:
mat_a = np.array([[1, 2],
                  [3, 4]])
print(f"mat_a \nshape : {mat_a.shape} \nndim : {mat_a.ndim} \n{mat_a}")
transpose_a = mat_a.transpose()
print(f"transpose_a \nshape : {transpose_a.shape} \nndim : {transpose_a.ndim} \n{transpose_a}")


mat_a 
shape : (2, 2) 
ndim : 2 
[[1 2]
 [3 4]]
transpose_a 
shape : (2, 2) 
ndim : 2 
[[1 3]
 [2 4]]
