In [13]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator 
from sklearn.metrics import accuracy_score
import numpy as np 
import pandas as pd 

class MyFakeClassifier(BaseEstimator):
    def fit(self, X, y):
        pass 
    
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)

digit = load_digits()
print(digit.data)
y = (digit.target==7).astype(int)
print(digit.target)
print(digit.data.shape)
print(digit.target.shape)
X_train, X_test, y_train, y_test = train_test_split(digit.data, y, random_state=11)


[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]
(1797, 64)
(1797,)


In [7]:
print(f"size of label test dataset {y_test.shape} ")
print("distribution of test dataset label 0 and 1")
print(pd.Series(y_test).value_counts())

fakeclf = MyFakeClassifier()
fakeclf.fit(X_train, y_train)
fakepred = fakeclf.predict(X_test)
print("{:.3f}".format(accuracy_score(y_test, fakepred)))

size of label test dataset (450,) 
distribution of test dataset label 0 and 1
0    405
1     45
dtype: int64
0.900
