In [2]:
import sklearn

print(sklearn.__version__)

1.0.2


In [43]:
import numpy as np 
from sklearn.base import BaseEstimator

class MyDummyClassifier(BaseEstimator):
    
    def fit(self, X, y=None):
        pass 
    
    def predict(self, X):
        pred = np.zeros((X.shape[0], 1))
        
        for i in range(X.shape[0]):
            if X["Sex"].iloc[i] == 1 :
                pred[i] = 0
                
            else : 
                pred[i] = 1
        
        return pred 

In [47]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder

def fillna_feature(df):
    df["Age"].fillna(df["Age"].mean(), inplace=True)
    df["Cabin"].fillna("N", inplace=True) 
    df["Embarked"].fillna("N", inplace=True)
    
    return df 

def drop_feature(df):
    df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)
    return df 

def encoding_feature(df):
    df["Cabin"] = df["Cabin"].str[:1]
    featrues = ["Cabin","Sex","Embarked"]
    
    for feature in featrues:
        le = LabelEncoder()
        le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df 

def transform_feature(df):
    df = fillna_feature(df)
    df = drop_feature(df)
    df = encoding_feature(df)
    df
    return df 



In [48]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 

titanic_df = pd.read_csv("Data\\titanic_train.csv")

y_titanic_df = titanic_df["Survived"]
X_titanic_df = titanic_df.drop("Survived", axis=1)
X_titanic_df = transform_feature(X_titanic_df)

X_train, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size=0.2, random_state=0)
myclf = MyDummyClassifier()

myclf.fit(X_train, y_train) 

myprections = myclf.predict(X_test)
print("Accurancy of Dummy Classifier {0: .4f}".format(accuracy_score(y_test, myprections)))
X_titanic_df

Accurancy of Dummy Classifier  0.7877


Pclass  Sex        Age  SibSp  Parch     Fare  Cabin  Embarked
0         3    1  22.000000      1      0   7.2500      7         3
1         1    0  38.000000      1      0  71.2833      2         0
2         3    0  26.000000      0      0   7.9250      7         3
3         1    0  35.000000      1      0  53.1000      2         3
4         3    1  35.000000      0      0   8.0500      7         3
..      ...  ...        ...    ...    ...      ...    ...       ...
886       2    1  27.000000      0      0  13.0000      7         3
887       1    0  19.000000      0      0  30.0000      1         3
888       3    0  29.699118      1      2  23.4500      7         3
889       1    1  26.000000      0      0  30.0000      2         0
890       3    1  32.000000      0      0   7.7500      7         2

[891 rows x 8 columns]

In [49]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator 
from sklearn.metrics import accuracy_score
import numpy as np 
import pandas as pd 

class MyFakeClassifier(BaseEstimator):
    def fit(self, X, y):
        pass 
    
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)

digit = load_digits()
print(digit.data)
y = (digit.target==7).astype(int)
print(digit.target)
print(digit.data.shape)
print(digit.target.shape)
X_train, X_test, y_train, y_test = train_test_split(digit.data, y, random_state=11)


[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]
(1797, 64)
(1797,)


In [50]:
print(f"size of label test dataset {y_test.shape} ")
print("distribution of test dataset label 0 and 1")
print(pd.Series(y_test).value_counts())

fakeclf = MyFakeClassifier()
fakeclf.fit(X_train, y_train)
fakepred = fakeclf.predict(X_test)
print("{:.3f}".format(accuracy_score(y_test, fakepred)))

size of label test dataset (450,) 
distribution of test dataset label 0 and 1
0    405
1     45
dtype: int64
0.900


#### Confusion Matrix 

In [51]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, fakepred)

array([[405,   0],
       [ 45,   0]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

print(f"precision score {precision_score(y_test, fakepred)}")
print(f"recall score {recall_score(y_test, fakepred)}")

precision score 0.0
recall score 0.0


In [55]:
from sklearn.metrics import accuracy_score, precision_score , recall_score , confusion_matrix

def get_clf_eval(y_test , pred):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    print('confusion matrix')
    print(confusion)
    print("\naccuracy: {0:.4f} \npredision: {1:.4f} \nrecall: {2:.4f}".format(accuracy , precision ,recall))

In [56]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
import warnings 
warnings.filterwarnings('ignore')

titanic_df = pd.read_csv('Data\\titanic_train.csv')
y_titanic_df = titanic_df['Survived']
X_titanic_df= titanic_df.drop('Survived', axis=1)
X_titanic_df = transform_feature(X_titanic_df)

X_train, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size=0.20, random_state=11)

lr_clf = LogisticRegression(solver='liblinear')

lr_clf.fit(X_train, y_train)
pred = lr_clf.predict(X_test)
get_clf_eval(y_test , pred)

confusion matrix
[[108  10]
 [ 14  47]]

accuracy: 0.8659 
predision: 0.8246 
recall: 0.7705
