#### Data Preprocessing
```Garbage In Garbage out``` 
- Data cleanging 
    - Delete unnecessary data

- Null/Nan value handling
    - Machine learning does not allow null values.

- Data encoding(label, one-hot encoding)
    - convert string to numbers

- Data scaling
    - Standardization 
    - Nomarlization 

- Remove Outliter 

- Feature selection
extraction, processing




#### Data Encoding 
- Label Encoding 

In [8]:
from sklearn.preprocessing import LabelEncoder 

items = ["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(f"labels \n type : {type(labels)} \nshape : {labels.shape} \n{labels}")

labels 
 type : <class 'numpy.ndarray'> 
shape : (8,) 
[0 1 4 5 3 3 2 2]


In [9]:
print(f"encoder.classes_ : {encoder.classes_}")

encoder.classes_ : ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [13]:
print(f"Decoding original value :{encoder.inverse_transform([0, 1, 2, 3, 4, 5])}")

Decoding original value :['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


#### Data Encoding 
- One Hot Encoding 

In [23]:
from sklearn.preprocessing import OneHotEncoder 
import numpy as np 

items = ["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

items = np.array(items).reshape(8, 1)
print(f"items \nshape : {items.shape} \ntype : {type(items)} \n{items}")

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
print(oh_labels)
print(oh_labels.toarray())
print(oh_labels.shape)

items 
shape : (8, 1) 
type : <class 'numpy.ndarray'> 
[['TV']
 ['냉장고']
 ['전자렌지']
 ['컴퓨터']
 ['선풍기']
 ['선풍기']
 ['믹서']
 ['믹서']]
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


#### Pandas get_dummies

In [28]:
import pandas as pd 

df = pd.DataFrame({"items":["TV", "냉장고", "전자렌지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]})
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [29]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0         1          0         0          0           0          0
1         0          1         0          0           0          0
2         0          0         0          0           1          0
3         0          0         0          0           0          1
4         0          0         0          1           0          0
5         0          0         0          1           0          0
6         0          0         1          0           0          0
7         0          0         1          0           0          0